services:
  - type: web
    name: openai-proxy
    plan: free
    runtime: image
    image:
      url: ghcr.io/berriai/litellm:main-stable
    
    # This command bypasses the memory-heavy setup script
    startCommand: "python -m litellm.proxy.proxy_server"

    # Your environment variables as you provided them
    envVars:
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_DfIOpaq01bLm@ep-fancy-smoke-aakzbvhf-pooler.westus3.azure.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: LITELLM_MASTER_KEY
        value: sk-3toFpFmGgHCRtHSYeC7DCxnESPcjTopnNh8tjQyM
      - key: LITELLM_SALT_KEY
        value: sk-PnWABG8jXNkpvwpclO7S5O1Pr2Hr
      - key: STORE_MODEL_IN_DB
        value: "True"

    healthCheckPath: /health/liveliness
    autoDeploy: true
