services:
  - type: web
    name: openai-proxy
    plan: free
    runtime: image
    image:
      url: ghcr.io/berriai/litellm:main-stable
    envVars:
      - key: PORT
        value: 4000
    # 👇 This block was moved back to the correct indentation level
    envVarGroups:
      - name: litellm-secrets
    healthCheckPath: /health/liveliness
    autoDeploy: true
