services:
  - type: web
    name: openai-proxy
    plan: free
    runtime: image
    image:
      url: ghcr.io/berriai/litellm:main-stable
    envVars:
      - key: PORT # Sets the non-secret port variable
        value: 4000
    envVarGroups:
      - name: litellm-secrets # Securely links your secret keys
    healthCheckPath: /health/liveliness
    autoDeploy: true
